title: 'Monopohl'
description: "Monopohl Elektroinstallateure"
#baseurl: "/monopohlisten.de"
url: "https://monopohlisten.de/"

header_pages:
  - index.md
  - ueber.md
  - music.md
  - merch.md

style: dark

# <link rel="shortcut icon" type="image/x-icon" href="favicon.ico">

footer: '<a href="https://soundcloud.com/monopohlisten">soundcloud</a> <a href="https://instagram.com/monopohlisten">ig</a> <a href="https://monopohlisten.bandcamp.com/">bandcamp</a> <a href="https://www.youtube.com/@monopohlisten">yt</a>'

# Build settings
markdown: kramdown
theme: jekyll-theme-console
future: true

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
